### ISSUE TITLE
MPI errors when core is greater than 4

### ISSUE THREAD

**Issue by GMW99** [rosalindfranklininstitute/DosNa#2]
When running the command: ` mpiexec -n 4  python test_dataset_mpi.py --backend hdf5 --engine mpi --connection .` Everything runs fine and all the tests pass successfully. However when running anything above  `4` i.e `-n 5` the test `test_non_overlapping_set` fails with the following errors. 

```
test_non_overlapping_set (__main__.MpiDatasetTest) ... ok
test_non_overlapping_set (__main__.MpiDatasetTest) ... ok
test_non_overlapping_set (__main__.MpiDatasetTest) ... ok
test_non_overlapping_set (__main__.MpiDatasetTest) ... ok
test_non_overlapping_set (__main__.MpiDatasetTest) ... 2021-09-01 14:14:36,666 - __main__ - INFO - DatasetTest: hdf5, mpi, {'name': '.'}
2021-09-01 14:14:36,666 - __main__ - INFO - DatasetTest: hdf5, mpi, {'name': '.'}
2021-09-01 14:14:36,666 - __main__ - INFO - DatasetTest: hdf5, mpi, {'name': '.'}
2021-09-01 14:14:36,666 - __main__ - INFO - DatasetTest: hdf5, mpi, {'name': '.'}
2021-09-01 14:14:36,666 - __main__ - INFO - DatasetTest: hdf5, mpi, {'name': '.'}
ERROR
ERROR
ERROR

======================================================================
ERROR: test_non_overlapping_set (__main__.MpiDatasetTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_dataset_mpi.py", line 100, in test_non_overlapping_set
    self.data[x_start:x_stop, ...] * 3 + 5
  File "/home/crc99971/github/DosNa/dosna/engines/base.py", line 102, in __setitem__
    self.set_data(values, slices=slices)
  File "/home/crc99971/github/DosNa/dosna/engines/cpu.py", line 70, in set_data
    self.set_chunk_data(idx, values[gslice], slices=cslice)
  File "/home/crc99971/github/DosNa/dosna/backends/base.py", line 156, in set_chunk_data
    self.get_chunk(idx)[slices] = values
  File "/home/crc99971/github/DosNa/dosna/backends/base.py", line 335, in __setitem__
    self.set_data(values, slices=slices)
  File "/home/crc99971/github/DosNa/dosna/backends/hdf5.py", line 180, in set_data
    with h5.File(self.path, 'a') as file_handle:
  File "/home/crc99971/miniconda3/envs/py2/lib/python2.7/site-packages/h5py/_hl/files.py", line 408, in __init__
    swmr=swmr)
  File "/home/crc99971/miniconda3/envs/py2/lib/python2.7/site-packages/h5py/_hl/files.py", line 187, in make_fid
    fid = h5f.create(name, h5f.ACC_EXCL, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 108, in h5py.h5f.create
IOError: Unable to create file (unable to open file: name = '/home/crc99971/github/DosNa/dosna/tests/./NotADataset/chunk_0_0_0.h5', errno = 17, error message = 'File exists', flags = 15, o_flags = c2)

----------------------------------------------------------------------
Ran 7 tests in 1.539s

FAILED (errors=1)
ERROR

======================================================================
ERROR: test_non_overlapping_set (__main__.MpiDatasetTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_dataset_mpi.py", line 100, in test_non_overlapping_set
    self.data[x_start:x_stop, ...] * 3 + 5
  File "/home/crc99971/github/DosNa/dosna/engines/base.py", line 102, in __setitem__
    self.set_data(values, slices=slices)
  File "/home/crc99971/github/DosNa/dosna/engines/cpu.py", line 70, in set_data
    self.set_chunk_data(idx, values[gslice], slices=cslice)
  File "/home/crc99971/github/DosNa/dosna/backends/base.py", line 156, in set_chunk_data
    self.get_chunk(idx)[slices] = values
  File "/home/crc99971/github/DosNa/dosna/backends/base.py", line 335, in __setitem__
    self.set_data(values, slices=slices)
  File "/home/crc99971/github/DosNa/dosna/backends/hdf5.py", line 180, in set_data
    with h5.File(self.path, 'a') as file_handle:
  File "/home/crc99971/miniconda3/envs/py2/lib/python2.7/site-packages/h5py/_hl/files.py", line 408, in __init__
    swmr=swmr)
  File "/home/crc99971/miniconda3/envs/py2/lib/python2.7/site-packages/h5py/_hl/files.py", line 187, in make_fid
    fid = h5f.create(name, h5f.ACC_EXCL, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 108, in h5py.h5f.create
IOError: Unable to create file (unable to open file: name = '/home/crc99971/github/DosNa/dosna/tests/./NotADataset/chunk_0_0_0.h5', errno = 17, error message = 'File exists', flags = 15, o_flags = c2)

----------------------------------------------------------------------
Ran 7 tests in 1.538s

FAILED (errors=1)

======================================================================
ERROR: test_non_overlapping_set (__main__.MpiDatasetTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_dataset_mpi.py", line 100, in test_non_overlapping_set
    self.data[x_start:x_stop, ...] * 3 + 5
  File "/home/crc99971/github/DosNa/dosna/engines/base.py", line 102, in __setitem__
    self.set_data(values, slices=slices)
  File "/home/crc99971/github/DosNa/dosna/engines/cpu.py", line 70, in set_data
    self.set_chunk_data(idx, values[gslice], slices=cslice)
  File "/home/crc99971/github/DosNa/dosna/backends/base.py", line 156, in set_chunk_data
    self.get_chunk(idx)[slices] = values
  File "/home/crc99971/github/DosNa/dosna/backends/base.py", line 335, in __setitem__
    self.set_data(values, slices=slices)
  File "/home/crc99971/github/DosNa/dosna/backends/hdf5.py", line 180, in set_data
    with h5.File(self.path, 'a') as file_handle:
  File "/home/crc99971/miniconda3/envs/py2/lib/python2.7/site-packages/h5py/_hl/files.py", line 408, in __init__
    swmr=swmr)
  File "/home/crc99971/miniconda3/envs/py2/lib/python2.7/site-packages/h5py/_hl/files.py", line 187, in make_fid
    fid = h5f.create(name, h5f.ACC_EXCL, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 108, in h5py.h5f.create
IOError: Unable to create file (unable to open file: name = '/home/crc99971/github/DosNa/dosna/tests/./NotADataset/chunk_0_0_0.h5', errno = 17, error message = 'File exists', flags = 15, o_flags = c2)

----------------------------------------------------------------------
Ran 7 tests in 1.539s

FAILED (errors=1)

======================================================================
ERROR: test_non_overlapping_set (__main__.MpiDatasetTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_dataset_mpi.py", line 71, in tearDown
    self.connection_handle.del_dataset(self.fake_dataset)
  File "/home/crc99971/github/DosNa/dosna/engines/mpi.py", line 56, in del_dataset
    dataset = self.get_dataset(name)
  File "/home/crc99971/github/DosNa/dosna/engines/mpi.py", line 52, in get_dataset
    dataset = self.instance.get_dataset(name)
  File "/home/crc99971/github/DosNa/dosna/backends/hdf5.py", line 85, in get_dataset
    'Dataset at `%s` does not exist' % self.relpath(name))
DatasetNotFoundError: Dataset at `/home/crc99971/github/DosNa/dosna/tests/./NotADataset` does not exist

----------------------------------------------------------------------
Ran 7 tests in 1.541s

ERROR

======================================================================
ERROR: test_non_overlapping_set (__main__.MpiDatasetTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_dataset_mpi.py", line 71, in tearDown
    self.connection_handle.del_dataset(self.fake_dataset)
  File "/home/crc99971/github/DosNa/dosna/engines/mpi.py", line 56, in del_dataset
    dataset = self.get_dataset(name)
  File "/home/crc99971/github/DosNa/dosna/engines/mpi.py", line 52, in get_dataset
    dataset = self.instance.get_dataset(name)
  File "/home/crc99971/github/DosNa/dosna/backends/hdf5.py", line 85, in get_dataset
    'Dataset at `%s` does not exist' % self.relpath(name))
DatasetNotFoundError: Dataset at `/home/crc99971/github/DosNa/dosna/tests/./NotADataset` does not exist

----------------------------------------------------------------------
Ran 7 tests in 1.539s

FAILED (errors=1)
FAILED (errors=1)
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpiexec detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[14593,1],1]
  Exit code:    1
--------------------------------------------------------------------------
 ```
 
 The core errors here are the `DatasetNotFoundError` and `IOError: Unable to create file`  the 3 `ERROR` represents the `IOError` that is being generated.

**Comment by GMW99** [comment]
This error also occurs when using ceph as the backend which suggests it's an MPI issue instead of a backend issue. ```mpiexec -n 8 python3 test_dataset_mpi.py --engine mpi --backend ceph --connection dosna --connection-options conffile=ceph.conf ```  error: 

```
test_non_overlapping_set (__main__.MpiDatasetTest) ... 2021-09-02 15:01:36,803 - __main__ - INFO - DatasetTest: ceph, mpi, {'name': 'dosna', 'conffile': 'ceph.conf'}
ERROR

======================================================================
ERROR: test_non_overlapping_set (__main__.MpiDatasetTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_dataset_mpi.py", line 71, in tearDown
    self.connection_handle.del_dataset(self.fake_dataset)
  File "/home/crc99971/github/rfi/DosNa/dosna/engines/mpi.py", line 56, in del_dataset
    dataset = self.get_dataset(name)
  File "/home/crc99971/github/rfi/DosNa/dosna/engines/mpi.py", line 52, in get_dataset
    dataset = self.instance.get_dataset(name)
  File "/home/crc99971/github/rfi/DosNa/dosna/backends/ceph.py", line 92, in get_dataset
    shape = str2shape(self.ioctx.get_xattr(name, 'shape').decode())
  File "rados.pyx", line 595, in rados.requires.wrapper.validate_func
  File "rados.pyx", line 3421, in rados.Ioctx.get_xattr
rados.ObjectNotFound: [errno 2] RADOS object not found (Failed to get xattr b'shape')

----------------------------------------------------------------------
Ran 7 tests in 4.370s

FAILED (errors=1)
ERROR

======================================================================
ERROR: test_non_overlapping_set (__main__.MpiDatasetTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_dataset_mpi.py", line 71, in tearDown
    self.connection_handle.del_dataset(self.fake_dataset)
  File "/home/crc99971/github/rfi/DosNa/dosna/engines/mpi.py", line 56, in del_dataset
    dataset = self.get_dataset(name)
  File "/home/crc99971/github/rfi/DosNa/dosna/engines/mpi.py", line 52, in get_dataset
    dataset = self.instance.get_dataset(name)
  File "/home/crc99971/github/rfi/DosNa/dosna/backends/ceph.py", line 92, in get_dataset
    shape = str2shape(self.ioctx.get_xattr(name, 'shape').decode())
  File "rados.pyx", line 595, in rados.requires.wrapper.validate_func
  File "rados.pyx", line 3421, in rados.Ioctx.get_xattr
rados.ObjectNotFound: [errno 2] RADOS object not found (Failed to get xattr b'shape')

----------------------------------------------------------------------
Ran 7 tests in 4.368s

FAILED (errors=1)
ERROR

======================================================================
ERROR: test_non_overlapping_set (__main__.MpiDatasetTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_dataset_mpi.py", line 71, in tearDown
    self.connection_handle.del_dataset(self.fake_dataset)
  File "/home/crc99971/github/rfi/DosNa/dosna/engines/mpi.py", line 56, in del_dataset
    dataset = self.get_dataset(name)
  File "/home/crc99971/github/rfi/DosNa/dosna/engines/mpi.py", line 52, in get_dataset
    dataset = self.instance.get_dataset(name)
  File "/home/crc99971/github/rfi/DosNa/dosna/backends/ceph.py", line 92, in get_dataset
    shape = str2shape(self.ioctx.get_xattr(name, 'shape').decode())
  File "rados.pyx", line 595, in rados.requires.wrapper.validate_func
  File "rados.pyx", line 3421, in rados.Ioctx.get_xattr
rados.ObjectNotFound: [errno 2] RADOS object not found (Failed to get xattr b'shape')

----------------------------------------------------------------------
Ran 7 tests in 4.369s

FAILED (errors=1)
ERROR

======================================================================
ERROR: test_non_overlapping_set (__main__.MpiDatasetTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_dataset_mpi.py", line 71, in tearDown
    self.connection_handle.del_dataset(self.fake_dataset)
  File "/home/crc99971/github/rfi/DosNa/dosna/engines/mpi.py", line 56, in del_dataset
    dataset = self.get_dataset(name)
  File "/home/crc99971/github/rfi/DosNa/dosna/engines/mpi.py", line 52, in get_dataset
    dataset = self.instance.get_dataset(name)
  File "/home/crc99971/github/rfi/DosNa/dosna/backends/ceph.py", line 92, in get_dataset
    shape = str2shape(self.ioctx.get_xattr(name, 'shape').decode())
  File "rados.pyx", line 595, in rados.requires.wrapper.validate_func
  File "rados.pyx", line 3421, in rados.Ioctx.get_xattr
rados.ObjectNotFound: [errno 2] RADOS object not found (Failed to get xattr b'shape')

----------------------------------------------------------------------
Ran 7 tests in 4.369s

FAILED (errors=1)
ERROR

======================================================================
ERROR: test_non_overlapping_set (__main__.MpiDatasetTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_dataset_mpi.py", line 71, in tearDown
    self.connection_handle.del_dataset(self.fake_dataset)
  File "/home/crc99971/github/rfi/DosNa/dosna/engines/mpi.py", line 56, in del_dataset
    dataset = self.get_dataset(name)
  File "/home/crc99971/github/rfi/DosNa/dosna/engines/mpi.py", line 52, in get_dataset
    dataset = self.instance.get_dataset(name)
  File "/home/crc99971/github/rfi/DosNa/dosna/backends/ceph.py", line 92, in get_dataset
    shape = str2shape(self.ioctx.get_xattr(name, 'shape').decode())
  File "rados.pyx", line 595, in rados.requires.wrapper.validate_func
  File "rados.pyx", line 3421, in rados.Ioctx.get_xattr
rados.ObjectNotFound: [errno 2] RADOS object not found (Failed to get xattr b'shape')

----------------------------------------------------------------------
Ran 7 tests in 4.369s

FAILED (errors=1)
ERROR

======================================================================
ERROR: test_non_overlapping_set (__main__.MpiDatasetTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_dataset_mpi.py", line 71, in tearDown
    self.connection_handle.del_dataset(self.fake_dataset)
  File "/home/crc99971/github/rfi/DosNa/dosna/engines/mpi.py", line 56, in del_dataset
    dataset = self.get_dataset(name)
  File "/home/crc99971/github/rfi/DosNa/dosna/engines/mpi.py", line 52, in get_dataset
    dataset = self.instance.get_dataset(name)
  File "/home/crc99971/github/rfi/DosNa/dosna/backends/ceph.py", line 93, in get_dataset
    dtype = self.ioctx.get_xattr(name, 'dtype').decode()
  File "rados.pyx", line 595, in rados.requires.wrapper.validate_func
  File "rados.pyx", line 3421, in rados.Ioctx.get_xattr
rados.ObjectNotFound: [errno 2] RADOS object not found (Failed to get xattr b'dtype')

----------------------------------------------------------------------
Ran 7 tests in 4.368s

FAILED (errors=1)
ERROR

======================================================================
ERROR: test_non_overlapping_set (__main__.MpiDatasetTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_dataset_mpi.py", line 71, in tearDown
    self.connection_handle.del_dataset(self.fake_dataset)
  File "/home/crc99971/github/rfi/DosNa/dosna/engines/mpi.py", line 56, in del_dataset
    dataset = self.get_dataset(name)
  File "/home/crc99971/github/rfi/DosNa/dosna/engines/mpi.py", line 52, in get_dataset
    dataset = self.instance.get_dataset(name)
  File "/home/crc99971/github/rfi/DosNa/dosna/backends/ceph.py", line 92, in get_dataset
    shape = str2shape(self.ioctx.get_xattr(name, 'shape').decode())
  File "rados.pyx", line 595, in rados.requires.wrapper.validate_func
  File "rados.pyx", line 3421, in rados.Ioctx.get_xattr
rados.ObjectNotFound: [errno 2] RADOS object not found (Failed to get xattr b'shape')

----------------------------------------------------------------------
Ran 7 tests in 4.372s

FAILED (errors=1)

```
The core error is rados.ObjectNotFound however I believe this is a red herring. And instead, an MPI issue that causes the said problem.

**Comment by GMW99** [comment]
With further investigation, the chunk grid dimension is 4 therefore any `n` above 4 would not work as `4 // 4 + x where x>=1` would be 0  as `\\` is a floor division operation, such that chunks_per_process = 0. This means that when `n > 4`  it will not work as the start = (4+x) * 0 * 32  which equals 0  so the start and stop will return empty datasets which means no object can be found.  


```
def test_non_overlapping_set(self):
        chunks_per_process = self.dataset.chunk_grid[0] // mpi_size()

        x_start = mpi_rank() * chunks_per_process * DATA_CHUNK_SIZE[0]
        if mpi_rank() == mpi_size() - 1:
            x_stop = self.dataset.shape[0]
        else:
            x_stop = (mpi_rank() + 1) * chunks_per_process * DATA_CHUNK_SIZE[0]
        if x_start < self.dataset.shape[0]:
            self.dataset[x_start:x_stop, ...] = \
                self.data[x_start:x_stop, ...] * 3 + 5
        mpi_barrier()
        if mpi_is_root():
            expected = self.data * 3 + 5
            result = self.dataset[...]
            np.testing.assert_array_equal(result, expected)
        mpi_barrier()
```
