### ISSUE TITLE
Error in test_slice_content Test

### ISSUE THREAD

**Issue by GMW99** [rosalindfranklininstitute/DosNa#4]
When running the tests test_slice_content errors with the following error:
```
test_slice_content (__main__.DatasetTest) ... 2021-09-01 14:38:46,093 - __main__ - INFO - DatasetTest: ram, cpu, {'name': 'test-dosna'}
ERROR

======================================================================
ERROR: test_slice_content (__main__.DatasetTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_dataset.py", line 107, in test_slice_content
    np.testing.assert_array_equal(self.dataset[slice_],
  File "/home/crc99971/github/DosNa/dosna/engines/base.py", line 99, in __getitem__
    return self.get_data(slices)
  File "/home/crc99971/github/DosNa/dosna/engines/cpu.py", line 53, in get_data
    return np.squeeze(output, axis=squeeze_axis)
  File "/home/crc99971/miniconda3/envs/py2/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 1388, in squeeze
    return squeeze(axis=axis)
TypeError: 'list' object cannot be interpreted as an index

----------------------------------------------------------------------
```

This error seems to be a type issue where a list is provided where it shouldn't be.

**Comment by GMW99** [comment]
This error also occurs when using python3
```
test_slice_content (__main__.DatasetTest) ... 2021-09-01 14:43:54,407 - __main__ - INFO - DatasetTest: ram, cpu, {'name': 'test-dosna'}
ERROR

======================================================================
ERROR: test_slice_content (__main__.DatasetTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_dataset.py", line 107, in test_slice_content
    np.testing.assert_array_equal(self.dataset[slice_],
  File "/home/crc99971/github/DosNa/dosna/engines/base.py", line 99, in __getitem__
    return self.get_data(slices)
  File "/home/crc99971/github/DosNa/dosna/engines/cpu.py", line 53, in get_data
    return np.squeeze(output, axis=squeeze_axis)
  File "<__array_function__ internals>", line 6, in squeeze
  File "/home/crc99971/miniconda3/envs/py3/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 1508, in squeeze
    return squeeze(axis=axis)
TypeError: 'list' object cannot be interpreted as an integer

----------------------------------------------------------------------
Ran 10 tests in 0.366s

FAILED (errors=1)
```

**Comment by GMW99** [comment]
The error is the file `DosNa/dosna/engines/base.py` and is due to the axis being passed a list instead of a tuple. 

```
squeeze_axis = []
        for index, slice_ in enumerate(slices):
            if isinstance(slice_, int):
                final_slices.append(slice(slice_, slice_ + 1))
                squeeze_axis.append(index)
            elif isinstance(slice_, slice):
               .
               .
               .
            else:
                raise Exception('Invalid type `{}` in slicing, only integer or'
                                ' slices are supported'.format(type(slice_)))

        if squeeze:
            return final_slices, squeeze_axis
```
As tuples are immutable and appending happens it would make sense to convert the squeeze_axis array to a tuple at the end. However, this is worth testing that it is more performant.

**Comment by GMW99** [comment]
This has closed as the fix worked and the test passed in python 2 and 3.
